### ISSUE TITLE
Covmat for cross-correlation

### ISSUE THREAD

**Issue by jodunkley** [xzackli/nawrapper#11]
I think the current analytic covmat calculation assumes that map1 and map2 have the same signal, i.e. that the cross and the autos all have signal power TT. If we want to take a cross-correlation of two different T maps (e.g. at different frequencies) is there a way to adapt the covmat calculation in a simple way?

**Comment by xzackli** [comment]
Hey @jodunkley here are some quick thoughts on this. Apologies if you've thought about this already, but it's helpful for me to type it out and clarify.

On fields A and B, on the same mask for simplicity, $\rm{var}(C_\ell^{AB})$ is a function of the masks $\Xi$ multiplied by the spectra combined as 

$$\left[ C_\ell^{AA} C_\ell^{BB} + (C_\ell^{AB})^2 \right] \Xi_{\ell \ell}$$

A pair of Gaussian random fields $A,B$ have three numbers: $C_\ell^{AA}, C_\ell^{AB}, C_\ell^{BB}$. If there is a shared signal, these numbers can be transformed into three numbers of equivalent information: a signal $C_{\ell}^{AB}$ and two noise $N_{\ell}^{AA}$ and $N_{\ell}^{AA}$. 

This is particularly nice for CMB analysis because the covariance requires the true spectrum $C_{\ell}$, but all you have is an unbiased estimate from the sample variance i.e. $\hat{C_\ell}$. Splitting it into noise and signal lets you enforce $N_\ell \geq 0$, which helps you get sensible results in the cosmic variance regime in a blind way (just from the data).

I can add a quick interface that puts the onus on the user to robustly estimate smooth versions of $C_\ell^{AA}, C_\ell^{AB}, C_\ell^{BB}$.

**Comment by xzackli** [comment]
Assuming the smoothing worked correctly, then nawrapper estimates the below numbers and then substitutes them into the expression above.

$$C_{\ell}^{AA} = \text{smooth}( \hat{C}_{\ell}^{AB} ) + \left|\text{smooth}( \hat{C}_{\ell}^{AA}) - \text{smooth}( \hat{C}_{\ell}^{AB})\right|$$

$$C_{\ell}^{BB} = \text{smooth}( \hat{C}_{\ell}^{AB} ) + \left|\text{smooth}( \hat{C}_{\ell}^{BB}) - \text{smooth}( \hat{C}_{\ell}^{AB})\right|$$

As long as $C_\ell^{AA}, C_{\ell}^{BB} \geq C_\ell^{AB}$ then I think it should work without modification in the case where the signal is not shared.

**Comment by xzackli** [comment]
@jodunkley I ran some sims today, and I was able to think of some common situations where this will be necessary. I'll put together a PR tomorrow so this option is available.

**Comment by xzackli** [comment]
This was resolved in PR #12 and demonstrated in this [notebook](https://github.com/xzackli/nawrapper/blob/master/notebooks/Covariance%20Simulations%20different%20signals.ipynb).
